version: '3'

services:
  # Контейнер с Node.js
  app:
    build:
      context: ./backend/
      dockerfile: Dockerfile
    tty: true
    working_dir: /app
    volumes:
      - ./app:/opt/server
    env_file:
      - .env
    expose:
      - '3000:3000'
    depends_on:
      - db

  # Контейнер с базой данных
  db:
    image: postgres:12-alpine
    environment:
      - POSTGRES_USER=${PGUSER}
      - POSTGRES_PASSWORD=${PGPASSWORD}
      - POSTGRES_DB=vue-db
      - POSTGRES_PORT=${DB_PORT}
    volumes:
      - ./postgres:/var/lib/postgresql/data
    expose:
      - '5432:5544'
    restart: always

  # Контейнер с nginx
  nginx:
    container_name: proxy_nginx
    depends_on:
      - app
      - db
    image: nginx:latest
    ports:
      - '80:80'
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    restart: always
